---
name: Test

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: master

jobs:
  smoke: 
    name: Smoke tests
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run Smoke tests
        uses: ./.github/actions/run-eden-test
        with:
          file_system: "ext4"
          tpm_enabled: false
          suite: "smoke.tests.txt"

  networking: 
    name: Networking test suite
    needs: smoke
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run Networking tests
        uses: ./.github/actions/run-eden-test
        with:
          file_system: "ext4"
          tpm_enabled: false
          suite: "networking.tests.txt"

  storage: 
    name: Storage test suite
    needs: smoke
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run Storage tests
        uses: ./.github/actions/run-eden-test
        with:
          file_system: "ext4"
          tpm_enabled: false
          suite: "storage.tests.txt"

  lpc-loc:
    name: LPC LOC test suite
    needs: smoke
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run LPC LOC tests
        uses: ./.github/actions/run-eden-test
        with:
          file_system: "ext4"
          tpm_enabled: false
          suite: "lpc-loc.tests.txt"

  eve-upgrade:
    name: EVE upgrade test suite
    needs: smoke
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run EVE upgrade tests
        uses: ./.github/actions/run-eden-test
        with:
          file_system: "ext4"
          tpm_enabled: false
          suite: "eve-upgrade.tests.txt"

  user-apps:
    name: User apps test suite
    needs: smoke
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run User apps upgrade tests
        uses: ./.github/actions/run-eden-test
        with:
          file_system: "ext4"
          tpm_enabled: false
          suite: "user-apps.tests.txt"
