u--
name: Static validation
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]

jobs:
  validation:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: make validate
        run: |
          make validate
